### ISSUE TITLE
Simplify Extensions API

### ISSUE THREAD

**Issue by friday** [Ulauncher/Ulauncher#829]
- [x] Handle events with extension class methods. `on_query_change`, `on_item_enter`, `on_preferences_update` and `on_unload` #936 and #1057
- [x] Replace `PreferencesEvent` with  `__init__` #1047
- [x] Avoid pointless getters and wrappers for extensions #1057 and 54d4607cd14b290c49b7ed5733b96c51398a16e1

**Comment by friday** [comment]
Changed it to 6.0.0 milestone so I remember to revisit it for that, but realistically it'll have to wait longer so more time can be put into it.

**Comment by friday** [comment]
Removed things from the list that have been better detailed in #864 and #966 since.

**Comment by friday** [comment]
This issue is now complete though other issues/PRs. Further improvements to the extension API to simplify won't be needed for v6, but maybe other type of improvements.
