### ISSUE TITLE
V5->V6 migration script

### ISSUE THREAD

**Issue by friday** [Ulauncher/Ulauncher#845]
I've been making most of these changes backward compatible, but will be doing some backward incompatible changes that will lose state and settings, and leave useless files left in your system.

- [ ] "Launch at Login" is implemented in a completely different way, using systemd instead of XDG Autostart, and currently the old autostart file is just ignored and you need to enable "Launch at Login" even if you had it enabled before (see #808 and 6f390634d8dce0a8c4d266964b60c5646653cc42)
- [ ] data/media was renamed to data/icons (since it only had icons in it) and the paths were simplified overall, but the default shortcuts are generated and store the old paths, so to support this, the old paths have been symlinked to the new paths, just for the shortcuts, but we can easily do a find/replace in shortcuts.json instead.
- [ ] desktop_dirs.db is not used any more and can be deleted as of #835
- [ ] app_cache.db can be deleted too. It was only used for one purpose, and was replaced with a simpler solution 4344e422beb2ad2525ceefad1348977bb1a112d6
- [ ] app_stat_v2.db was replaced by app_stat_v3.db as of #835 (v3 uses desktop application ids instead of full paths, which is better, and you can run a script to get the id's from the full paths)
- [ ] All the `.db` files created with the KeyValueDb class except extension preferences are now stored in STATE_DIR  as of https://github.com/Ulauncher/Ulauncher/pull/846/commits/32d15c95c7e67453d8c24940f9ed7b7ee4263517 (and the `last.log` file too)
- [ ] Switching from Pickle to JSON #849
- [ ] `show-recent-apps` used to be a boolean, and in v5 was changed to integer, and `True` was converted to 3, and `False` to `0`. We should drop this support and add it to the conversion script.

**Comment by friday** [comment]
Closed by #1094

It doesn't strictly check all the boxes in this issue, but if it doesn't check them it's for a reason.
